import { ReactNode } from 'react'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

import { ChakraProvider } from 'providers'
import { theme } from 'styles'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Fusão Estelar',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="pt-br">
            <body>
                <ChakraProvider theme={theme}>{children}</ChakraProvider>
            </body>
        </html>
    )
}
